name: tests

on:
  push:
    branches:
      - develop
      - releases/*
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Test the app (unit test)
        run: ./gradlew clean test
      - name: Prepare configuration for integration tests
        env:
          CL_URL: ${{ secrets.TESTS_CL_URL }}
          CL_LGN: ${{ secrets.TESTS_CL_LGN }}
          CL_PWD: ${{ secrets.TESTS_CL_PWD }}
          CL_AID: ${{ secrets.TESTS_CL_AID }}
          SDK_CONFIG: ${{ secrets.TESTS_SDK_CONFIG }}
          ER_URL: ${{ secrets.TESTS_ER_URL }}
          OP_URL: ${{ secrets.TESTS_OP_URL }}
          IN_URL: ${{ secrets.TESTS_IN_URL }}
        run: echo -e tests.sdk.cloudServerUrl="$CL_URL"\\ntests.sdk.cloudServerLogin="$CL_LGN"\\ntests.sdk.cloudServerPassword="$CL_PWD"\\ntests.sdk.cloudApplicationId="$CL_AID"\\ntests.sdk.enrollmentServerUrl="$ER_URL"\\ntests.sdk.operationsServerUrl="$OP_URL"\\ntests.sdk.inboxServerUrl="$IN_URL"\\ntests.sdk.sdkConfig="$SDK_CONFIG"" > configs/integration-tests.properties
      - name: Test the app (integration tests)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew clean connectedAndroidTest --info
