name: tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Test the app (unit test)
        run: ./gradlew clean test
      - name: Create emulator
        run: echo no | avdmanager create avd --force --name testAVD --abi google_apis/x86 --package 'system-images;android-29;google_apis;x86'
      - name: Start the emulator
        run: emulator @testAVD &
      - name: Wait for emulator to boot
        run: avd wait-for-device
      - name: Prepare configuration for integration tests
        env:
          APP_ID: ${{ secrets.TESTS_APP_ID }}
          APP_KEY: ${{ secrets.TESTS_APP_KEY }}
          APP_SECRET: ${{ secrets.TESTS_APP_SECRET }}
          MASTER_SERVER_PUBLIC_KEY: ${{ secrets.TESTS_MASTER_SERVER_PUBLIC_KEY }}
          PA_URL: ${{ secrets.TESTS_PA_URL }}
          ER_URL: ${{ secrets.TESTS_ER_URL }}
          OP_URL: ${{ secrets.TESTS_OP_URL }}
          NS_URL: ${{ secrets.TESTS_NS_URL }}
        run: echo tests.sdk.paServerUrl="$PA_URL"\\ntests.sdk.nextStepServerUrl="NS_URL"\\ntests.sdk.enrollmentServerUrl="ER_URL"\\ntests.sdk.operationsServerUrl="OP_URL"\\ntests.sdk.appKey="$APP_KEY"\\ntests.sdk.appSecret="$APP_SECRET"\\ntests.sdk.masterServerPublicKey="$MASTER_SERVER_PUBLIC_KEY"\\ntests.sdk.appId="$APP_ID" > configs/integration-tests.properties
      - name: Test the app (integration tests)
        run: ./gradlew clean connectedAndroidTest
