name: tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Test the app
        run: ./gradlew clean test
